services:
  api:
    image: mcsystems/news-search-api:${IMAGE_TAG}
    deploy:
      replicas: ${API_REPLICAS}
    environment:
      INDEXES: ${INDEXES}
      ESHOSTS: ${ESHOSTS}
      ESOPTS: ${ESOPTS}
      ELASTICSEARCH_INDEX_NAME_PREFIX: ${ELASTICSEARCH_INDEX_NAME_PREFIX}
      TERMFIELDS: ${TERMFIELDS}
      TERMAGGRS: ${TERMAGGRS}
      SENTRY_DSN: ${SENTRY_DSN}
      SENTRY_ENVIRONMENT: ${SENTRY_ENVIRONMENT}
      TITLE: ${NEWS_SEARCH_UI_TITLE}
    ports:
      - ${API_PORT}:8000
    volumes:
      - .:/app

  ui:
    image: mcsystems/news-search-api:${IMAGE_TAG}
    environment:
      APIURL: http://api:8000/v1
    ports:
      - ${UI_PORT}:8501
    volumes:
      - .:/app
    depends_on:
      - api
    command: streamlit run ui.py
