services:
  api:
    image: mcsystems/news-search-api:${IMAGE_TAG}
    environment:
      INDEXES: ${INDEXES}
      ESHOSTS: ${ESHOSTS}
      ESOPTS: ${ESOPTS}
      ELASTICSEARCH_INDEX_NAME_PREFIX: ${ELASTICSEARCH_INDEX_NAME_PREFIX}
      TERMFIELDS: ${TERMFIELDS}
      TERMAGGRS: ${TERMAGGRS}
    ports:
      - 8000:8000
    volumes:
      - .:/app

  ui:
    image: mcsystems/news-search-api:${IMAGE_TAG}
    environment:
      APIURL: http://api:8000/v1
    ports:
      - 8501:8501
    volumes:
      - .:/app
    depends_on:
      - api
    command: streamlit run ui.py
